### ISSUE TITLE
reference to webpush_client.js not reliable

### ISSUE THREAD

**Issue by AdriwanKenoby** [bpolaszek/webpush-bundle#1]
In webpush_client.js

```
var thisScript = document.getElementsByTagName('script')[document.getElementsByTagName('script').length - 1];
```
Should be replace by ```var thisScript = document.getElementById('pushClient');``` with the pushClient ID added to your script tag in the template.

Because I work with OroCRM application which use requirejs and I can't guarantee that this script is the last one on the document.

Same problem with [https://github.com/bpolaszek/bentools-pusher-bundle](https://github.com/bpolaszek/bentools-pusher-bundle)

**Comment by bpolaszek** [comment]
Hi @AdriwanKenoby,

That's a good approach indeed. Instead of relying on an id (that might create an id collision), I would rather try on a data-attribute:
```html
<script src="webpush_client.js" data-pushclient></script>
```
```javascript
// webpush_client.js
var thisScript = document.querySelector('script[data-pushclient]');
```

What's your opinion?
