### ISSUE TITLE
Working with Webpack Encore

### ISSUE THREAD

**Issue by vezuwio** [bpolaszek/webpush-bundle#10]
Will you plan to modify js code, so that it can work with Webpack Encore?

**Comment by bpolaszek** [comment]
Hi @vezuwio,

I'm currently working on a SF4 project that uses webpack encore in which I'll need this bundle in a very near future.

So, I'll probably work on it within the next weeks. 

Nevertheless, I'm not a JS expert (I never published an NPM package or any JS library), and the current JS implementation is not satisfying to my eyes (hard to figure out who does what) so any help would be really appreciated.

Ben

**Comment by bpolaszek** [comment]
@vezuwio Just to let you know, I have started rewriting JS from scratch, trying to make it compatible with webpack. Stay tuned.

**Comment by bpolaszek** [comment]
Hi @vezuwio, 

I just released the new 0.4 version. Beware that it has several [breaking changes](https://github.com/bpolaszek/webpush-bundle/releases/tag/0.4) but the main advantage is that the JS part has been completely removed in favor of a standalone component: [webpush-client](https://www.npmjs.com/package/webpush-client) (not natively compatible with 0.3, but can work after some little tuning if you can't upgrade easily).
