### ISSUE TITLE
Incorrect parameter description in services.xml

### ISSUE THREAD

**Issue by wRLSS** [bpolaszek/webpush-bundle#11]
Configuration file `services.xml` doesn't seem to be correctly configured in the part of

```
    <parameters>
        <parameter id="bentools_webpush.public_key"></parameter>
        <parameter id="bentools_webpush.private_key"></parameter>
    </parameters>
```

I believe it's a mistake and it should state `key` instead of `id`. 
Having `id` here introduces some random integer keys with no value inside symfony ParameterBag

**Comment by wRLSS** [comment]
Any chance it can be released to avoid spreading usage of stability/fork override?

**Comment by bpolaszek** [comment]
@wRLSS I'm actively working on the 0.4 version, but some little breaking changes are to expect.

**Comment by bpolaszek** [comment]
0.3.4 released, anyway :)
