### ISSUE TITLE
Bug in example UserSubscriptionManagerInterface

### ISSUE THREAD

**Issue by stephrsh** [bpolaszek/webpush-bundle#13]
Hi,

just to tell you that i tried you example UserSubscriptionManagerInterface class, but i had a fatal error.

I just add `=[]` and to get it works

` public function factory(UserInterface $user, string $subscriptionHash, array $subscription, array $options): UserSubscriptionInterface`
    
to

` public function factory(UserInterface $user, string $subscriptionHash, array $subscription, array $options=[]): UserSubscriptionInterface`

**Comment by bpolaszek** [comment]
Hey @stephrsh, 

Thanks for pointing it out. :thumbsup:
