### ISSUE TITLE
upgrade to web-push-php 5.1

### ISSUE THREAD

**Issue by davidgorges** [bpolaszek/webpush-bundle#14]
Hi,
nice work with this bundle! Any chance you plan to upgrade to the current version of `minishlink/web-push` (5.1) or are willing to receive a PR?
Shouldn't be too much effort, reading the changelog https://github.com/web-push-libs/web-push-php/releases

**Comment by bpolaszek** [comment]
Hey @davidgorges - `minishlink/web-push` 5.1 is now supported through `bentools/webpush-bundle` 0.5.

Thank you!
Ben

**Comment by davidgorges** [comment]
Thanks a lot!
