### ISSUE TITLE
webpush:generate:keys command does not exist

### ISSUE THREAD

**Issue by tv78-coder** [bpolaszek/webpush-bundle#15]
Hello, i am using SF 4.3. After i install this bundle, the `php bin/console webpush:generate:keys` is undefined and i don't see the configuration file either. How should i do?

**Comment by bpolaszek** [comment]
Hey there,

It looks like the bundle is no longer automatically registered in `config/bundles.php`, I was able to reproduce this. Can you please add it manually?

I'll try to have a look at this  later.

**Comment by bpolaszek** [comment]
Fixed in 0.5.1.
