### ISSUE TITLE
How /webpush route work?

### ISSUE THREAD

**Issue by tv78-coder** [bpolaszek/webpush-bundle#16]
```
bentools_webpush:
    resource: '@WebPushBundle/Resources/config/routing.xml'
    prefix: /webpush
```

I put the code above in `config\annotations\routes.yaml` since SF 4.3 does not have `config/routing.yaml`.  But when i visit /webpush or using webpush-client it give me 404 Not Found response.

I put the webpush-client js code in my index.html.twig:
```
var WebPushClient;
    if (WebPushClientFactory.isSupported()) {
        WebPushClientFactory.create({
            serviceWorkerPath: "{{ asset('js/webpush-sw.min.js') }}", // Public path to the service worker
            serverKey: 'BDM1aPZTQoKtjL5IqlLGdpxTjuA_B5JvGfs0QpwAetjnN_EZF_1WLV6sTcg6WZGV4OBmDhMPi5Df9dw6uzGa3kQ', // https://developers.google.com/web/fundamentals/push-notifications/web-push-protocol#application_server_keys
            subscribeUrl: '/webpush', // Optionnal - your application URL to store webpush subscriptions
        })
            .then(Client => {
                WebPushClient = Client;
                console.log(Client);
                WebPushClient.subscribe();
            })
        ;
    }
```

Is there anything wrong about the setup?

**Comment by bpolaszek** [comment]
Mh, looks like a trailing slash is required now. Can you please try with `subscribeUrl: '/webpush/'` ?

**Comment by tv78-coder** [comment]
> Mh, looks like a trailing slash is required now. Can you please try with `subscribeUrl: '/webpush/'` ?

Ok now it will add user to subscription in doctrine. 

How can i fire the `NotificationSenderListener` in my controller? I've tried dispatcher but it seems i don't receive any notification in my chrome after execute:
```
// ......

$event = new OrderPlacedEvent($order);
$dispatcher = new EventDispatcher();
$dispatcher->dispatch($event, OrderPlacedEvent::NAME);
```
