### ISSUE TITLE
Symfony 6.0 support

### ISSUE THREAD

**Issue by zogs** [bpolaszek/webpush-bundle#34]
Bonjour Benoit ! Any plan to support SF6 ?

**Comment by bpolaszek** [comment]
Hey @zogs,

Would be great, but CI doesn't work anymore, as I no longer use Travis. I should migrate to Github Actions first, to ensure everything's still working and that SF6 compatiblity doesn't introduce regressions, but I'm quite a bit overwhelmed at the very moment, unfortunately 🙁 

PRs are still welcome :-)

**Comment by encreinformatique** [comment]
> I should migrate to Github Actions first, to ensure everything's still working and that SF6 compatiblity doesn't introduce regressions, but I'm quite a bit overwhelmed at the very moment, unfortunately

I opened a [PR for Github Actions](https://github.com/bpolaszek/webpush-bundle/pull/39). Hope that helps.

**Comment by bpolaszek** [comment]
> Hello 🙂
> 
> I managed to make my fork SF6 compatible ! Can make a pull request if you want Tests are runing and registrations/notifications are working fine in my usecase. Probably need some more test though...

PR very welcome 🙂

**Comment by pacoVela** [comment]
> Hello slightly_smiling_face
> 
> I managed to make my fork SF6 compatible ! Can make a pull request if you want Tests are runing and registrations/notifications are working fine in my usecase. Probably need some more test though...

Please make the PR ... :)
